FROM registry.redhat.io/rhel10/rhel-bootc:10.0-1747353195
RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
RUN dnf -y install cockpit
RUN systemctl enable cockpit.socket
