#FROM registry.redhat.io/rhel9/rhel-bootc
FROM registry.redhat.io/rhel10-beta/bootc-image-builder

RUN echo "%wheel        ALL=(ALL)       NOPASSWD: ALL" > /etc/sudoers.d/wheel-sudo
RUN dnf -y install httpd && \
    systemctl enable httpd && \
    mv /var/www /usr/share/www && \
    sed -ie 's,/var/www,/usr/share/www,' /etc/httpd/conf/httpd.conf
RUN echo "Welcome to a GHA built bootc-http instance!" > /usr/share/www/html/index.html
